// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swqhrplbnpfpleibpmke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3cWhycGxibnBmcGxlaWJwbWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTA5ODIsImV4cCI6MjA1OTA4Njk4Mn0.4k6JBypU2MDZWg9IM0NIMxs4ig89YgZehX6ZFF8KbWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);